service: sls-az-func-rest-api

provider:
  name: azure
  runtime: nodejs10.x
  region: ${opt:region, 'West US'}
  stage: ${opt:stage, 'dev'}
  prefix: ${opt:prefix, 'nestjs-serverless-azure'}
  apim: true

plugins:
  - serverless-azure-functions

package:
  exclude:
    - local.settings.json
    - .vscode/**

functions:
  azure-function:
    handler: dist/main/index
    events:
      - http: true
        x-azure-settings:
          authLevel: function
