service: nestjs-serverless-azure

provider:
  name: azure
  runtime: nodejs10.x
  region: ${opt:region, 'West US'}
  stage: ${opt:stage, 'dev'}
  prefix: ${opt:prefix, 'yashmurty'}
  apim:
    apis:
      # Name of the API
      - name: main-api
        subscriptionRequired: false
        # Display name
        displayName: Main API
        # Description of API
        description: The Main REST API
        # HTTP protocols allowed
        protocols:
          - https
        # Base path of API calls
        path: /
    backends:
      - name: main-backend
        url: api/v1

plugins:
  - serverless-azure-functions

package:
  exclude:
    - local.settings.json
    - .vscode/**

## NOTE: 
# 1 Upon originally adding the nestjs-azure-functions, a function.json file is created.
#   I have translated that file to the below azure function definition. For ref:
#   https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings
#   https://serverless.com/framework/docs/providers/azure/guide/events/
# 2 URL paths for the serverless functions are prefixed with "api" by default, e.g. /api/some/path. 
#   You can change this via a setting in host.json.
functions:
  main:
    handler: dist/main/index
    events:
      - http: true
        x-azure-settings:
          name: req
          authLevel: anonymous
          route: "{*segments}"
      - http: true
        x-azure-settings:
          direction: out
          name: res
    apim:
      api: main-api
      backend: main-backend
      operations:
        - method: all
          urlTemplate: /{*segments}
          templateParameters:
            - name: segments
              type: string