service: nestjs-serverless-azure

provider:
  name: azure
  runtime: nodejs10.x
  region: ${opt:region, 'West US'}
  stage: ${opt:stage, 'dev'}
  prefix: ${opt:prefix, 'yashmurty'}
  apim: true

plugins:
  - serverless-azure-functions

package:
  exclude:
    - local.settings.json
    - .vscode/**

 
# Even without manually adding the functions here, it seems to work out of the box.
# Possibly due to the plugin serverless-azure-functions and nest js package nestjs/azure-func-http.